apiVersion: apps/v1
kind: Deployment
metadata:
  name: MonoDeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MySelectorApp  # This is the label selector for matching Pods
  template:
    metadata:
      labels:
        app: MySelectorApp  # This label must match the selector
    spec:
      containers:
        - name: naveencontainer
          image: 423623829923.dkr.ecr.us-east-1.amazonaws.com/naveenrepo:latest
          ports:
            - containerPort: 8080
