apiVersion: apps/v1
kind: Deployment
metadata:
  name: MonoDeployment
  namespace: mynamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MySelectorApp
  template:
    metadata:
      labels:
        app: MySelectorTemplate
    spec:
      containers:
        - name: naveencontainer
          image: 423623829923.dkr.ecr.us-east-1.amazonaws.com/naveenrepo:latest
          ports:
            - containerPort: 8080
