apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-selector-app  # This is the label selector for matching Pods
  template:
    metadata:
      labels:
        app: my-selector-app  # This label must match the selector
    spec:
      containers:
        - name: naveencontainer
          image: 423623829923.dkr.ecr.us-east-1.amazonaws.com/naveenrepo:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: my-selector-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
